package com.saad.invitationmaker.features.home.models

data class DraftAllViews(
    var viewId: String? = "",
    var viewData: String? = "",
    var alignment: String? = "",
    var opacity: String? = "",
    var rotation: String? = "",
    var rotationX: String? = "",
    var rotationY: String? = "",
    var dRotationX: String? = "",
    var dRotationY: String? = "",
    var shadowAngleX: Float? = 0f,
    var shadowAngleY: Float? = 0f,
    var shadowBlur: Float? = 1f,
    var shadowColor: String? = "",
    var viewType: String? = "",
    var fontSize: String? = "",
    var font: String? = "",
    var letterSpacing: String? = "",
    var lineHeight: String? = "",
    var textStyle: String? = "",
    var color: String? = "",
    var xCoordinate: String? = "",
    var yCoordinate: String? = "",
    var width: String? = "",
    var height: String? = "",
    var priority: String? = "",
)
